#!/bin/bash

for function in _putchar _islower _isalpha _abs _isupper _isdigit _strlen _puts _strcpy _atoi _strcat _strncat _strncpy _strcmp _memset _memcpy _strchr _strspn _strpbrk _strstr; do
  echo "Creating function C file for $function..."
  cat <<EOF > $function.c
#include <stdio.h>

int $function(void);

int main(void) {
  return $function();
}
EOF
done
