#!/bin/bash

for function in putchar islower isalpha abs isupper isdigit strlen puts strcpy atoi strcat strncat strncpy strcmp memset memcpy strchr strspn strpbrk strstr; do
  echo "Creating function C file for $function..."
  cat <<EOF > _$function.c
#include "main.h"
#include <stdio.h>

/**
 * _$function - function prototype
 * Description: function prototype
 * Return: 0
 */

int _$function(void)
{
return (0);
}
EOF
done
